### ISSUE TITLE
Artifacts cannot be downloaded from Jitpack

### ISSUE THREAD

**Issue by neodiX42** [andreypfau/ton-kotlin#1]
Within Java project using Maven build dependency like it stated by Jitpack:
https://jitpack.io/#andreypfau/ton-kotlin
most artifacts cannot be downloaded. 
For example vesion "adnl-1840f76479-1" is ok, other fail.

**Comment by andreypfau** [comment]
Fixed: https://jitpack.io/#andreypfau/ton-kotlin/0868ad55ec
