### ISSUE TITLE
Coins.toString() incorrect results

### ISSUE THREAD

**Issue by mcnckc** [andreypfau/ton-kotlin#34]
If `Coins` variable stores at least 1 TON, function will return incorrect result, for example the following:
```
val nanoAmount: Long = 1_000_000_000
val coins = Coins.ofNano(nanoAmount)
coins.toString()
```
results in `1.999999999`

Let's look at the `toString()` code:

```
override fun toString(): String = buildString {
    val full = amount.value / NANOCOINS
    val decimal = amount.value - full
    append(full)
    append(".")
    append(decimal.toString().padStart(9, '0'))
}
```
In the line `val decimal = amount.value - full` the value in TON (`full`) is subtracted from the value in nanoTON (`amount.value`), which makes decimal part incorrect. In my opinion, changing to `val decimal = amount.value - full * NANOCOINS`, or `val decimal = amount.value % NANOCOINS` would fix the problem.

**Comment by AntonMeep** [comment]
Thank you for your report, it is spot on.

Moreover, entire logic behind toString() is not correct here as Coins() can hold amounts of currencies, for example jettons, that are not guaranteed to have 9 digits after the point. I will address this as well to make it more flexible.
