### ISSUE TITLE
java.util.Base64 breaks Android 25- compability

### ISSUE THREAD

**Issue by mcnckc** [andreypfau/ton-kotlin#49]
At least in file base64.kt - https://github.com/andreypfau/ton-kotlin/blob/main/ton-kotlin-crypto/src/jvmMain/kotlin/org/ton/crypto/base64.kt class `java.util.Base64` is used.
Unfortunately, this class was only added in API level 26 - https://developer.android.com/reference/java/util/Base64.
This makes impossible for apps, based on this library, to run on Android API level 25 or lower.
Possible solution could be to use `android.util.Base64` instead.

According to Android studio, 11,8% of current android devices have API level 25 or lower.

**Comment by andreypfau** [comment]
Fixed in fcac45071f
